# Generated by Django 4.2.30 on 2026-07-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0015_piece_taille_octets'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='notes_internes',
            field=models.TextField(blank=True, help_text="Usage interne à l'application : jamais reprises dans le rapport PDF. Contrairement à `commentaire`, ce champ n'alimente aucune sortie imprimée.", verbose_name='Notes internes'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Reprises dans la colonne « Observations » de la page de garde du SSDGPS.', verbose_name='Observations'),
        ),
    ]
